version: '3.5'

services:
  solver:
    image: ${APP_SOLVER_IMG}
    ports:
      - ${HTTP_PORT}:8080
    environment:
      TZ: "Europe/Moscow"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname==${NODE_HOSTNAME}"
  bot:
    image: ${APP_BOT_IMG}
    environment:
      TZ: "Europe/Moscow"
      EQ_TELEGRAM_TOKEN:
      CLIENT_EQ_URL:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname==${NODE_HOSTNAME}"

#secrets:  
#  npulse_telegram_token:
#    external: true

#volumes:
#  app_log:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=${NFS_DATA_SERVER},rw
#      device: ":/srv/nfs/srvSwarmData/npulse-watcher/log"
