version: '3.5'

services:
  solver:
    image: ${APP_SOLVER_IMG}
    ports:
      - ${HTTP_PORT}:8080
    environment:
      TZ: "Europe/Moscow"
    secrets:
      - seqllm_wolfram_appid
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constraints:
      #    - "node.hostname==${NODE_HOSTNAME}"
  bot:
    image: ${APP_BOT_IMG}
    environment:
      TZ: "Europe/Moscow"
      EQ_TELEGRAM_TOKEN:
      CLIENT_EQ_ADDR:
      CLIENT_EQ_PORT:
      PYTHONUNBUFFERED: 1
    secrets:
      - seqllm_telegram_token
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constraints:
      #    - "node.hostname==${NODE_HOSTNAME}"

secrets:
  seqllm_telegram_token:
    external: true
  seqllm_wolfram_appid:
    external: true

